// Copyright (c) 2025 zolnoor. All rights reserved.

#include "Actions/EditorActions.h"
#include "MCPCommonUtils.h"
#include "Editor.h"
#include "Editor/TransBuffer.h"
#include "EditorViewportClient.h"
#include "LevelEditorViewport.h"
#include "Engine/World.h"
#include "GameFramework/Actor.h"
#include "Engine/StaticMeshActor.h"
#include "Engine/DirectionalLight.h"
#include "Engine/PointLight.h"
#include "Engine/SpotLight.h"
#include "Camera/CameraActor.h"
#include "Kismet/GameplayStatics.h"
#include "FileHelpers.h"
#include "UObject/SavePackage.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "Engine/Blueprint.h"
#include "Engine/BlueprintGeneratedClass.h"
#include "Engine/SimpleConstructionScript.h"
#include "Engine/SCS_Node.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_Event.h"
#include "K2Node_FunctionEntry.h"
#include "K2Node_CustomEvent.h"
#include "K2Node_CallFunction.h"
#include "K2Node_VariableGet.h"
#include "K2Node_VariableSet.h"
#include "AssetSelection.h"
#include "ObjectTools.h"
#include "Subsystems/AssetEditorSubsystem.h"
#include "AssetToolsModule.h"
#include "IAssetTools.h"
#include "EditorAssetLibrary.h"
#include "ImageUtils.h"
#include "Misc/Base64.h"
#include "Misc/PackageName.h"
#include "MCPLogCapture.h"
#include "MCPBridge.h"
#include "UObject/ObjectRedirector.h"
#include "UObject/UnrealType.h"
#include "Async/Async.h"
#include "Containers/Ticker.h"
#include "HAL/PlatformMisc.h"
#include "Misc/DateTime.h"
#include "PlayInEditorDataTypes.h"
#include "Settings/LevelEditorPlaySettings.h"
#include "EngineUtils.h"
#include "Selection.h"



// ============================================================================
// FDescribeFullAction — Single-call comprehensive Blueprint snapshot
// ============================================================================

bool FDescribeFullAction::Validate(const TSharedPtr<FJsonObject>& Params, FMCPEditorContext& Context, FString& OutError)
{
	if (!Params->HasField(TEXT("blueprint_name")) && !Params->HasField(TEXT("asset_path")))
	{
		OutError = TEXT("Either 'blueprint_name' or 'asset_path' is required");
		return false;
	}
	return true;
}

TSharedPtr<FJsonObject> FDescribeFullAction::SerializePinCompact(const UEdGraphPin* Pin)
{
	if (!Pin || Pin->bHidden)
	{
		return nullptr;
	}

	TSharedPtr<FJsonObject> PinObj = MakeShared<FJsonObject>();
	PinObj->SetStringField(TEXT("pin_name"), Pin->PinName.ToString());
	PinObj->SetStringField(TEXT("direction"), Pin->Direction == EGPD_Input ? TEXT("input") : TEXT("output"));
	PinObj->SetStringField(TEXT("category"), Pin->PinType.PinCategory.ToString());

	if (Pin->PinType.PinSubCategoryObject.IsValid())
	{
		PinObj->SetStringField(TEXT("sub_type"), Pin->PinType.PinSubCategoryObject->GetName());
	}

	if (Pin->LinkedTo.Num() > 0)
	{
		TArray<TSharedPtr<FJsonValue>> LinkedArray;
		for (const UEdGraphPin* LinkedPin : Pin->LinkedTo)
		{
			if (!LinkedPin || !LinkedPin->GetOwningNode()) continue;
			TSharedPtr<FJsonObject> LinkedObj = MakeShared<FJsonObject>();
			LinkedObj->SetStringField(TEXT("node_id"), LinkedPin->GetOwningNode()->NodeGuid.ToString());
			LinkedObj->SetStringField(TEXT("pin_name"), LinkedPin->PinName.ToString());
			LinkedArray.Add(MakeShared<FJsonValueObject>(LinkedObj));
		}
		PinObj->SetArrayField(TEXT("linked_to"), LinkedArray);
	}

	if (!Pin->DefaultValue.IsEmpty())
	{
		PinObj->SetStringField(TEXT("default_value"), Pin->DefaultValue);
	}
	else if (!Pin->AutogeneratedDefaultValue.IsEmpty())
	{
		PinObj->SetStringField(TEXT("default_value"), Pin->AutogeneratedDefaultValue);
	}
	if (Pin->DefaultObject)
	{
		PinObj->SetStringField(TEXT("default_object"), Pin->DefaultObject->GetPathName());
	}

	return PinObj;
}

TSharedPtr<FJsonObject> FDescribeFullAction::SerializeGraph(UBlueprint* Blueprint, UEdGraph* Graph,
	bool bIncludePinDetails, bool bIncludeFunctionSignatures) const
{
	if (!Graph) return nullptr;

	TSharedPtr<FJsonObject> GraphObj = MakeShared<FJsonObject>();
	GraphObj->SetStringField(TEXT("name"), Graph->GetName());
	GraphObj->SetNumberField(TEXT("node_count"), Graph->Nodes.Num());

	TArray<TSharedPtr<FJsonValue>> NodesArray;
	TArray<TSharedPtr<FJsonValue>> EdgesArray;
	TSet<FString> SeenEdges;

	for (const UEdGraphNode* Node : Graph->Nodes)
	{
		if (!Node) continue;

		TSharedPtr<FJsonObject> NodeObj = MakeShared<FJsonObject>();
		NodeObj->SetStringField(TEXT("node_id"), Node->NodeGuid.ToString());
		NodeObj->SetStringField(TEXT("node_class"), Node->GetClass()->GetName());
		NodeObj->SetStringField(TEXT("node_title"), Node->GetNodeTitle(ENodeTitleType::FullTitle).ToString());
		NodeObj->SetNumberField(TEXT("pos_x"), Node->NodePosX);
		NodeObj->SetNumberField(TEXT("pos_y"), Node->NodePosY);

		if (!Node->NodeComment.IsEmpty())
		{
			NodeObj->SetStringField(TEXT("comment"), Node->NodeComment);
		}

		// Function signature (optional, for function call nodes)
		if (bIncludeFunctionSignatures)
		{
			if (const UK2Node_CallFunction* FuncNode = Cast<UK2Node_CallFunction>(Node))
			{
				if (const UFunction* Function = FuncNode->GetTargetFunction())
				{
					TSharedPtr<FJsonObject> SigObj = MakeShared<FJsonObject>();
					SigObj->SetStringField(TEXT("function_name"), Function->GetName());
					SigObj->SetStringField(TEXT("owner_class"),
						Function->GetOwnerClass() ? Function->GetOwnerClass()->GetName() : TEXT("Unknown"));
					SigObj->SetBoolField(TEXT("is_static"), Function->HasAnyFunctionFlags(FUNC_Static));
					SigObj->SetBoolField(TEXT("is_pure"), Function->HasAnyFunctionFlags(FUNC_BlueprintPure));
					NodeObj->SetObjectField(TEXT("function_signature"), SigObj);
				}
			}
		}

		// Pins — compact mode by default
		TArray<TSharedPtr<FJsonValue>> PinsArray;
		for (const UEdGraphPin* Pin : Node->Pins)
		{
			if (!Pin || Pin->bHidden) continue;

			TSharedPtr<FJsonObject> PinObj = SerializePinCompact(Pin);
			if (PinObj.IsValid())
			{
				// Add full PinType details only if requested
				if (bIncludePinDetails)
				{
					TSharedPtr<FJsonObject> PinTypeObj = MakeShared<FJsonObject>();
					PinTypeObj->SetStringField(TEXT("category"), Pin->PinType.PinCategory.ToString());
					if (Pin->PinType.PinSubCategory != NAME_None)
						PinTypeObj->SetStringField(TEXT("sub_category"), Pin->PinType.PinSubCategory.ToString());
					if (Pin->PinType.PinSubCategoryObject.Get())
						PinTypeObj->SetStringField(TEXT("sub_category_object"), Pin->PinType.PinSubCategoryObject->GetPathName());
					PinTypeObj->SetBoolField(TEXT("is_array"), Pin->PinType.IsArray());
					PinTypeObj->SetBoolField(TEXT("is_reference"), Pin->PinType.bIsReference);
					PinObj->SetObjectField(TEXT("pin_type"), PinTypeObj);
				}
				PinsArray.Add(MakeShared<FJsonValueObject>(PinObj));
			}

			// Collect edges (output pins only, deduplicated)
			if (Pin->Direction == EGPD_Output)
			{
				for (const UEdGraphPin* LinkedPin : Pin->LinkedTo)
				{
					if (!LinkedPin || !LinkedPin->GetOwningNode()) continue;
					FString EdgeKey = FString::Printf(TEXT("%s:%s->%s:%s"),
						*Node->NodeGuid.ToString(), *Pin->PinName.ToString(),
						*LinkedPin->GetOwningNode()->NodeGuid.ToString(), *LinkedPin->PinName.ToString());
					if (!SeenEdges.Contains(EdgeKey))
					{
						SeenEdges.Add(EdgeKey);
						TSharedPtr<FJsonObject> EdgeObj = MakeShared<FJsonObject>();
						EdgeObj->SetStringField(TEXT("from_node"), Node->NodeGuid.ToString());
						EdgeObj->SetStringField(TEXT("from_pin"), Pin->PinName.ToString());
						EdgeObj->SetStringField(TEXT("to_node"), LinkedPin->GetOwningNode()->NodeGuid.ToString());
						EdgeObj->SetStringField(TEXT("to_pin"), LinkedPin->PinName.ToString());
						EdgesArray.Add(MakeShared<FJsonValueObject>(EdgeObj));
					}
				}
			}
		}
		NodeObj->SetArrayField(TEXT("pins"), PinsArray);
		NodesArray.Add(MakeShared<FJsonValueObject>(NodeObj));
	}

	GraphObj->SetArrayField(TEXT("nodes"), NodesArray);
	GraphObj->SetNumberField(TEXT("edge_count"), EdgesArray.Num());
	GraphObj->SetArrayField(TEXT("edges"), EdgesArray);

	return GraphObj;
}

TSharedPtr<FJsonObject> FDescribeFullAction::ExecuteInternal(const TSharedPtr<FJsonObject>& Params, FMCPEditorContext& Context)
{
	UBlueprint* Blueprint = nullptr;

	if (Params->HasField(TEXT("asset_path")))
	{
		FString AssetPath = Params->GetStringField(TEXT("asset_path"));
		Blueprint = Cast<UBlueprint>(StaticLoadObject(UBlueprint::StaticClass(), nullptr, *AssetPath));
	}
	if (!Blueprint && Params->HasField(TEXT("blueprint_name")))
	{
		FString BlueprintName = Params->GetStringField(TEXT("blueprint_name"));
		Blueprint = FMCPCommonUtils::FindBlueprint(BlueprintName);
	}
	if (!Blueprint)
	{
		return CreateErrorResponse(TEXT("Blueprint not found"));
	}

	const bool bIncludePinDetails = GetOptionalBool(Params, TEXT("include_pin_details"), false);
	const bool bIncludeFunctionSignatures = GetOptionalBool(Params, TEXT("include_function_signatures"), false);

	TSharedPtr<FJsonObject> Result = MakeShared<FJsonObject>();

	// ---- Basic Info ----
	Result->SetStringField(TEXT("blueprint_name"), Blueprint->GetName());
	Result->SetStringField(TEXT("blueprint_path"), Blueprint->GetPathName());

	if (Blueprint->ParentClass)
	{
		Result->SetStringField(TEXT("parent_class"), Blueprint->ParentClass->GetName());
		Result->SetStringField(TEXT("parent_class_path"), Blueprint->ParentClass->GetPathName());
	}

	FString TypeStr;
	switch (Blueprint->BlueprintType)
	{
		case BPTYPE_Normal: TypeStr = TEXT("Normal"); break;
		case BPTYPE_Const: TypeStr = TEXT("Const"); break;
		case BPTYPE_MacroLibrary: TypeStr = TEXT("MacroLibrary"); break;
		case BPTYPE_Interface: TypeStr = TEXT("Interface"); break;
		case BPTYPE_LevelScript: TypeStr = TEXT("LevelScript"); break;
		case BPTYPE_FunctionLibrary: TypeStr = TEXT("FunctionLibrary"); break;
		default: TypeStr = TEXT("Unknown"); break;
	}
	Result->SetStringField(TEXT("blueprint_type"), TypeStr);

	FString CompileStatus;
	switch (Blueprint->Status)
	{
		case BS_UpToDate: CompileStatus = TEXT("UpToDate"); break;
		case BS_Dirty: CompileStatus = TEXT("Dirty"); break;
		case BS_Error: CompileStatus = TEXT("Error"); break;
		case BS_BeingCreated: CompileStatus = TEXT("BeingCreated"); break;
		default: CompileStatus = TEXT("Unknown"); break;
	}
	Result->SetStringField(TEXT("compile_status"), CompileStatus);

	// ---- Variables ----
	TArray<TSharedPtr<FJsonValue>> VarsArray;
	for (const FBPVariableDescription& VarDesc : Blueprint->NewVariables)
	{
		TSharedPtr<FJsonObject> VarObj = MakeShared<FJsonObject>();
		VarObj->SetStringField(TEXT("name"), VarDesc.VarName.ToString());
		VarObj->SetStringField(TEXT("type"), VarDesc.VarType.PinCategory.ToString());
		if (VarDesc.VarType.PinSubCategoryObject.IsValid())
			VarObj->SetStringField(TEXT("sub_type"), VarDesc.VarType.PinSubCategoryObject->GetName());
		if (VarDesc.VarType.IsArray())
			VarObj->SetStringField(TEXT("container"), TEXT("Array"));
		VarObj->SetBoolField(TEXT("is_instance_editable"), (VarDesc.PropertyFlags & CPF_Edit) != 0);
		if (!VarDesc.DefaultValue.IsEmpty())
			VarObj->SetStringField(TEXT("default_value"), VarDesc.DefaultValue);
		VarsArray.Add(MakeShared<FJsonValueObject>(VarObj));
	}
	Result->SetArrayField(TEXT("variables"), VarsArray);

	// ---- Components (SCS) ----
	TArray<TSharedPtr<FJsonValue>> ComponentsArray;
	if (Blueprint->SimpleConstructionScript)
	{
		TArray<USCS_Node*> AllNodes = Blueprint->SimpleConstructionScript->GetAllNodes();
		for (USCS_Node* SCSNode : AllNodes)
		{
			if (!SCSNode) continue;
			TSharedPtr<FJsonObject> CompObj = MakeShared<FJsonObject>();
			CompObj->SetStringField(TEXT("name"), SCSNode->GetVariableName().ToString());
			if (SCSNode->ComponentClass)
				CompObj->SetStringField(TEXT("class"), SCSNode->ComponentClass->GetName());
			if (!SCSNode->ParentComponentOrVariableName.IsNone())
				CompObj->SetStringField(TEXT("parent"), SCSNode->ParentComponentOrVariableName.ToString());
			ComponentsArray.Add(MakeShared<FJsonValueObject>(CompObj));
		}
	}
	Result->SetArrayField(TEXT("components"), ComponentsArray);

	// ---- Interfaces ----
	TArray<TSharedPtr<FJsonValue>> InterfacesArray;
	for (const FBPInterfaceDescription& InterfaceDesc : Blueprint->ImplementedInterfaces)
	{
		if (InterfaceDesc.Interface)
			InterfacesArray.Add(MakeShared<FJsonValueString>(InterfaceDesc.Interface->GetName()));
	}
	Result->SetArrayField(TEXT("implemented_interfaces"), InterfacesArray);

	// ---- All Graph Topologies ----
	TArray<TSharedPtr<FJsonValue>> AllGraphs;

	// Event Graphs (UbergraphPages)
	for (UEdGraph* Graph : Blueprint->UbergraphPages)
	{
		TSharedPtr<FJsonObject> GraphObj = SerializeGraph(Blueprint, Graph, bIncludePinDetails, bIncludeFunctionSignatures);
		if (GraphObj.IsValid())
		{
			GraphObj->SetStringField(TEXT("graph_type"), TEXT("EventGraph"));
			AllGraphs.Add(MakeShared<FJsonValueObject>(GraphObj));
		}
	}

	// Function Graphs
	for (UEdGraph* Graph : Blueprint->FunctionGraphs)
	{
		TSharedPtr<FJsonObject> GraphObj = SerializeGraph(Blueprint, Graph, bIncludePinDetails, bIncludeFunctionSignatures);
		if (GraphObj.IsValid())
		{
			GraphObj->SetStringField(TEXT("graph_type"), TEXT("Function"));
			AllGraphs.Add(MakeShared<FJsonValueObject>(GraphObj));
		}
	}

	// Macro Graphs
	for (UEdGraph* Graph : Blueprint->MacroGraphs)
	{
		TSharedPtr<FJsonObject> GraphObj = SerializeGraph(Blueprint, Graph, bIncludePinDetails, bIncludeFunctionSignatures);
		if (GraphObj.IsValid())
		{
			GraphObj->SetStringField(TEXT("graph_type"), TEXT("Macro"));
			AllGraphs.Add(MakeShared<FJsonValueObject>(GraphObj));
		}
	}

	Result->SetArrayField(TEXT("graphs"), AllGraphs);

	// Summary counts
	int32 TotalNodes = 0;
	int32 TotalEdges = 0;
	for (const auto& GraphVal : AllGraphs)
	{
		const TSharedPtr<FJsonObject>* GraphObjPtr;
		if (GraphVal->TryGetObject(GraphObjPtr) && GraphObjPtr)
		{
			TotalNodes += static_cast<int32>((*GraphObjPtr)->GetNumberField(TEXT("node_count")));
			TotalEdges += static_cast<int32>((*GraphObjPtr)->GetNumberField(TEXT("edge_count")));
		}
	}
	Result->SetNumberField(TEXT("total_graphs"), AllGraphs.Num());
	Result->SetNumberField(TEXT("total_nodes"), TotalNodes);
	Result->SetNumberField(TEXT("total_edges"), TotalEdges);

	return CreateSuccessResponse(Result);
}


